---
title: "01_In-Class_Activity-01"
author: "Naga Vemprala"
date: '2023-01-26'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r loading_helpers}
#source("helper_functions.r")
fetch_gender <- function () {
  factor(c("M", "F", "O"), labels = c("Male", "Female", "Other"))
}
```



## First in-class activity on R objects. 

#### Question: 1 
```{r chunk1, echo = F}
#source("helper_functions.r")

gender <- factor(c("M", "F"), labels = c("Male", "Female"))
print("Gender variable before calling function")
print("----------------------------------------")
print(gender)
print("----------------------------------------")
print("Gender variable After calling function")
print("----------------------------------------")
# Call the function fetch_gender and print it 

gender <- fetch_gender()
print(gender)

```

#### Question: 2
```{r chunk2}
# Vector 1 - Create a numeric vector of length 5 with the course ids 101, 255, 355, 461, 491
# Vector 2 - Create a character character vector of length 5 and provide the course titles for these 5 courses as, "Software Applications", "Introduction to OTM", "Decision Modeling and Analytics", "R Programming for Business and Analytics", "Intro to Text Analytics".
# Vector 3 - Create a first day of class vector (Make sure that this vector is a date vectors)
# Vector 4 - Create a start time vector (Make sure that this vector is a time vectors)
# Include date and time e.g., "2023-01-16 14:10:00"
# Vector 5 - Create a end time vector (Make sure that this vector is a time vectors)
# Vector 6 - Create a class frequency vector (a numerical vector, 1 represents the class meets once a week, 2 represents the class meets twice a week, etc.)
# Vector 7 - Create a class frequency character vector (R for Thursday, MWF for Monday-Wednesday-Friday class etc)
# Create a data frame using these above vectors

vector1 <- c(101, 255, 355, 461, 491)
vector2 <- c("Software Applications", "Introduction to OTM", 
             "Decision Modeling and Analytics", "R Programming for Business 
             Analytics", "Intro to Text Analytics")
vector3 <- c("2023-01-16", "2023-01-17","2023-01-18","2023-01-19","2023-01-20")
vector3 <- as.Date(vector3)
vector4 <- c("2023-01-16 12:10:00", "2023-01-17 14:10:00", 
             "2023-01-18 16:10:00","2023-01-19 18:10:00", 
             "2023-01-20 20:10:00")
vector5 <- c("2023-01-16 13:10:00", "2023-01-17 15:10:00", 
             "2023-01-18 17:10:00","2023-01-19 19:10:00", 
             "2023-01-20 21:10:00")
vector6 <- c(1L, 2L, 2L, 3L, 1L )
vector7 <- c("R", "TR", "TR", "MWF", "R")

df1 <- data.frame(vector1, vector2, vector3, vector4, vector5, vector6, vector7)
df1

library(lubridate)
start_date <- "2023-01-16"
start_date <- "01162023"
mdy(start_date)
class(ymd(start_date))

```

#### Question: 3
```{r}
# Create a function to read the first day of class as string and the class frequency to return the next day of the class in the week. 
# Implement switch case instead of a sequence of if-else statements  

#"2023-01-16", "MWF"

next_class <- function (date_as_string, class_frequency) {
  next_date <- switch(class_frequency,
                      "MWF" = as.Date(date_as_string) + 2,
                      "TR" = as.Date(date_as_string) + 2)
  next_date
}

next_class("2023-01-16", "MWF")

#inefficient code below
var2 <- "ASC"
var1 <-switch(var2,
              "AST" = "Assistant",
              "ASC" = "Associate",
              "Full" = "Full professor")
if (var2 == "AST") {
  var1 <- "Assistant"
} else if (var2 == "ASC") {
  var1 <- "Associate"
} else {
  
}

```


