---
title: "01_In-Class_Activity-02"
author: "Naga Vemprala"
date: '2023-01-26'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## In-class activity to read files  

#### Question: 1 
```{r chunk1, echo = F}
# Read the csv file into a dataframe using read.csv 
# Hint: Check the current path using getwd() 
# Also, unlike working with markdown files, we need to build the complete path for the file in order to read the file. 
# Print the first 6 records of the file read into a dataframe. Name the dataframe as housingPrices

getwd()

fileName <- paste("C:/Users/Reuben/OneDrive - University of Portland/Documents/intro_to_r_spr2023/Input/","in_class_melbourne_housing_prices.csv", sep = "")
df1 <- read.csv(fileName)
View(df1)

head(df1)

```

#### Question: 2
```{r chunk2}
# Print the summary of the housingPrices dataset  

summary(df1)

```

#### Question: 3
```{r}
# Print the minimum date of the "Date" column   
library(lubridate)
names(df1)
?names()

head(df1$Date)
typeof(df1$Date)
head(as.Date(df1$Date))

df1$Date # d/m/y
head(dmy(df1$Date))


df1$Date <- dmy(df1$Date)
typeof(df1$Date)
min(df1$Date)

```


#### Question: 4
```{r}
# Create a dataset containing only 2 bedroom houses 
# Print the summary of the dataset two_bedroom_houses
# Print the average price of the two bedroom houses 



head(df1[3])
df1[1,3]
nrow(df1)
my_numeric_vector <- 1:3
my_row_numbers <- 1:nrow(df1)
filter_condition <- my_row_numbers < 6

head(filter_condition, 10)

df1[filter_condition, 3]
df1[c(1,2,3,4,5,11,12), 3]
df1[c(1:5,11,12), 3]
filter_condition <- df1$Rooms == 2
# = assigning values
# == checks values

df2 <- df1[filter_condition, ]
View(df2)



```

